package main

const (
	BLOCKCHAIN_PORT      = 9119
	MAX_NODE_CONNECTIONS = 1000

	KEY_POW_COMPLEXITY      = 0
	TEST_KEY_POW_COMPLEXITY = 0

	BLOCK_POW_COMPLEXITY      = 1
	TEST_BLOCK_POW_COMPLEXITY = 1

	POW_PREFIX      = 0
	TEST_POW_PREFIX = 0
)
